[dgx13:83599:0:83599] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x448)
==== backtrace (tid:  83599) ====
 0  /opt/conda/envs/gdf/lib/libucs.so.0(ucs_handle_error+0x2fd) [0x7f7e2472c07d]
 1  /opt/conda/envs/gdf/lib/libucs.so.0(+0x2a274) [0x7f7e2472c274]
 2  /opt/conda/envs/gdf/lib/libucs.so.0(+0x2a43a) [0x7f7e2472c43a]
 3  /usr/lib/x86_64-linux-gnu/libpthread.so.0(+0x14420) [0x7f7ec5944420]
 4  /opt/conda/envs/gdf/lib/libucp.so.0(ucp_mem_type_unpack+0x14) [0x7f7e247ab6b4]
 5  /opt/conda/envs/gdf/lib/libucp.so.0(ucp_rndv_data_handler+0x4e9) [0x7f7e247d4839]
 6  /opt/conda/envs/gdf/lib/libuct.so.0(+0x203df) [0x7f7e246e63df]
 7  /opt/conda/envs/gdf/lib/libuct.so.0(+0x23838) [0x7f7e246e9838]
 8  /opt/conda/envs/gdf/lib/libucs.so.0(ucs_event_set_wait+0xb9) [0x7f7e247354a9]
 9  /opt/conda/envs/gdf/lib/libuct.so.0(uct_tcp_iface_progress+0x7d) [0x7f7e246e85dd]
10  /opt/conda/envs/gdf/lib/libucp.so.0(ucp_worker_progress+0x5a) [0x7f7e247a88da]
11  /opt/conda/envs/gdf/lib/python3.9/site-packages/ucp/_libs/ucx_api.cpython-39-x86_64-linux-gnu.so(+0x3206a) [0x7f7e2486106a]
12  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x37cb) [0x55ad4b50e6fb]
13  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x55ad4b50a094]
14  /opt/conda/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd9) [0x55ad4b51b519]
15  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55ad4b50b5c6]
16  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55ad4b51b7c2]
17  /opt/conda/envs/gdf/bin/python(+0x14de83) [0x55ad4b528e83]
18  /opt/conda/envs/gdf/bin/python(+0x258b2c) [0x55ad4b633b2c]
19  /opt/conda/envs/gdf/bin/python(+0xead05) [0x55ad4b4c5d05]
20  /opt/conda/envs/gdf/bin/python(+0x1377f3) [0x55ad4b5127f3]
21  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x59f9) [0x55ad4b510929]
22  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55ad4b51b7c2]
23  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55ad4b50b5c6]
24  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55ad4b51b7c2]
25  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55ad4b50b5c6]
26  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55ad4b51b7c2]
27  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55ad4b50b5c6]
28  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55ad4b51b7c2]
29  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55ad4b50b5c6]
30  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x55ad4b50a094]
31  /opt/conda/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd9) [0x55ad4b51b519]
32  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x11f8) [0x55ad4b50c128]
33  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x55ad4b50a094]
34  /opt/conda/envs/gdf/bin/python(+0x14dccb) [0x55ad4b528ccb]
35  /opt/conda/envs/gdf/bin/python(PyObject_Call+0xbc) [0x55ad4b52944c]
36  /opt/conda/envs/gdf/bin/python(+0x21110e) [0x55ad4b5ec10e]
37  /opt/conda/envs/gdf/bin/python(_PyObject_MakeTpCall+0x2ec) [0x55ad4b51377c]
38  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x37cb) [0x55ad4b50e6fb]
39  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55ad4b51b7c2]
40  /opt/conda/envs/gdf/bin/python(+0x14ddac) [0x55ad4b528dac]
41  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x37cb) [0x55ad4b50e6fb]
42  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55ad4b51b7c2]
43  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55ad4b50b5c6]
44  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x55ad4b50a094]
45  /opt/conda/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd9) [0x55ad4b51b519]
46  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55ad4b50b5c6]
47  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55ad4b51b7c2]
48  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x3e2) [0x55ad4b50b312]
49  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x55ad4b50a094]
50  /opt/conda/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd9) [0x55ad4b51b519]
51  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x11f8) [0x55ad4b50c128]
52  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x55ad4b50a094]
53  /opt/conda/envs/gdf/bin/python(_PyEval_EvalCodeWithName+0x48) [0x55ad4b509d68]
54  /opt/conda/envs/gdf/bin/python(PyEval_EvalCodeEx+0x39) [0x55ad4b509d19]
55  /opt/conda/envs/gdf/bin/python(PyEval_EvalCode+0x1b) [0x55ad4b5b707b]
56  /opt/conda/envs/gdf/bin/python(+0x208fca) [0x55ad4b5e3fca]
57  /opt/conda/envs/gdf/bin/python(+0x205353) [0x55ad4b5e0353]
58  /opt/conda/envs/gdf/bin/python(PyRun_StringFlags+0x9a) [0x55ad4b5d816a]
59  /opt/conda/envs/gdf/bin/python(PyRun_SimpleStringFlags+0x3c) [0x55ad4b5d805c]
60  /opt/conda/envs/gdf/bin/python(Py_RunMain+0x267) [0x55ad4b5d7297]
61  /opt/conda/envs/gdf/bin/python(Py_BytesMain+0x37) [0x55ad4b5aaf07]
=================================
[dgx13:83583:0:83583] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x448)
==== backtrace (tid:  83583) ====
 0  /opt/conda/envs/gdf/lib/libucs.so.0(ucs_handle_error+0x2fd) [0x7efca13bc07d]
 1  /opt/conda/envs/gdf/lib/libucs.so.0(+0x2a274) [0x7efca13bc274]
 2  /opt/conda/envs/gdf/lib/libucs.so.0(+0x2a43a) [0x7efca13bc43a]
 3  /usr/lib/x86_64-linux-gnu/libpthread.so.0(+0x14420) [0x7efd4672c420]
 4  /opt/conda/envs/gdf/lib/libucp.so.0(ucp_mem_type_unpack+0x14) [0x7efca143b6b4]
 5  /opt/conda/envs/gdf/lib/libucp.so.0(ucp_rndv_data_handler+0x4e9) [0x7efca1464839]
 6  /opt/conda/envs/gdf/lib/libuct.so.0(+0x203df) [0x7efca13763df]
 7  /opt/conda/envs/gdf/lib/libuct.so.0(+0x23838) [0x7efca1379838]
 8  /opt/conda/envs/gdf/lib/libucs.so.0(ucs_event_set_wait+0xb9) [0x7efca13c54a9]
 9  /opt/conda/envs/gdf/lib/libuct.so.0(uct_tcp_iface_progress+0x7d) [0x7efca13785dd]
10  /opt/conda/envs/gdf/lib/libucp.so.0(ucp_worker_progress+0x5a) [0x7efca14388da]
11  /opt/conda/envs/gdf/lib/python3.9/site-packages/ucp/_libs/ucx_api.cpython-39-x86_64-linux-gnu.so(+0x3206a) [0x7efca14f106a]
12  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x37cb) [0x561e9b72a6fb]
13  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x561e9b726094]
14  /opt/conda/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd9) [0x561e9b737519]
15  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x561e9b7275c6]
16  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x561e9b7377c2]
17  /opt/conda/envs/gdf/bin/python(+0x14de83) [0x561e9b744e83]
18  /opt/conda/envs/gdf/bin/python(+0x258b2c) [0x561e9b84fb2c]
19  /opt/conda/envs/gdf/bin/python(+0xead05) [0x561e9b6e1d05]
20  /opt/conda/envs/gdf/bin/python(+0x1377f3) [0x561e9b72e7f3]
21  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x59f9) [0x561e9b72c929]
22  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x561e9b7377c2]
23  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x561e9b7275c6]
24  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x561e9b7377c2]
25  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x561e9b7275c6]
26  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x561e9b7377c2]
27  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x561e9b7275c6]
28  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x561e9b7377c2]
29  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x561e9b7275c6]
30  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x561e9b726094]
31  /opt/conda/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd9) [0x561e9b737519]
32  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x11f8) [0x561e9b728128]
33  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x561e9b726094]
34  /opt/conda/envs/gdf/bin/python(+0x14dccb) [0x561e9b744ccb]
35  /opt/conda/envs/gdf/bin/python(PyObject_Call+0xbc) [0x561e9b74544c]
36  /opt/conda/envs/gdf/bin/python(+0x21110e) [0x561e9b80810e]
37  /opt/conda/envs/gdf/bin/python(_PyObject_MakeTpCall+0x2ec) [0x561e9b72f77c]
38  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x37cb) [0x561e9b72a6fb]
39  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x561e9b7377c2]
40  /opt/conda/envs/gdf/bin/python(+0x14ddac) [0x561e9b744dac]
41  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x37cb) [0x561e9b72a6fb]
42  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x561e9b7377c2]
43  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x561e9b7275c6]
44  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x561e9b726094]
45  /opt/conda/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd9) [0x561e9b737519]
46  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x561e9b7275c6]
47  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x561e9b7377c2]
48  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x3e2) [0x561e9b727312]
49  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x561e9b726094]
50  /opt/conda/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd9) [0x561e9b737519]
51  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x11f8) [0x561e9b728128]
52  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x561e9b726094]
53  /opt/conda/envs/gdf/bin/python(_PyEval_EvalCodeWithName+0x48) [0x561e9b725d68]
54  /opt/conda/envs/gdf/bin/python(PyEval_EvalCodeEx+0x39) [0x561e9b725d19]
55  /opt/conda/envs/gdf/bin/python(PyEval_EvalCode+0x1b) [0x561e9b7d307b]
56  /opt/conda/envs/gdf/bin/python(+0x208fca) [0x561e9b7fffca]
57  /opt/conda/envs/gdf/bin/python(+0x205353) [0x561e9b7fc353]
58  /opt/conda/envs/gdf/bin/python(PyRun_StringFlags+0x9a) [0x561e9b7f416a]
59  /opt/conda/envs/gdf/bin/python(PyRun_SimpleStringFlags+0x3c) [0x561e9b7f405c]
60  /opt/conda/envs/gdf/bin/python(Py_RunMain+0x267) [0x561e9b7f3297]
61  /opt/conda/envs/gdf/bin/python(Py_BytesMain+0x37) [0x561e9b7c6f07]
=================================
[dgx13:83575:0:83575] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x448)
==== backtrace (tid:  83575) ====
 0  /opt/conda/envs/gdf/lib/libucs.so.0(ucs_handle_error+0x2fd) [0x7f2e4373207d]
 1  /opt/conda/envs/gdf/lib/libucs.so.0(+0x2a274) [0x7f2e43732274]
 2  /opt/conda/envs/gdf/lib/libucs.so.0(+0x2a43a) [0x7f2e4373243a]
 3  /usr/lib/x86_64-linux-gnu/libpthread.so.0(+0x14420) [0x7f2ee4a90420]
 4  /opt/conda/envs/gdf/lib/libucp.so.0(ucp_mem_type_unpack+0x14) [0x7f2e437b16b4]
 5  /opt/conda/envs/gdf/lib/libucp.so.0(ucp_rndv_data_handler+0x4e9) [0x7f2e437da839]
 6  /opt/conda/envs/gdf/lib/libuct.so.0(+0x203df) [0x7f2e436ec3df]
 7  /opt/conda/envs/gdf/lib/libuct.so.0(+0x23838) [0x7f2e436ef838]
 8  /opt/conda/envs/gdf/lib/libucs.so.0(ucs_event_set_wait+0xb9) [0x7f2e4373b4a9]
 9  /opt/conda/envs/gdf/lib/libuct.so.0(uct_tcp_iface_progress+0x7d) [0x7f2e436ee5dd]
10  /opt/conda/envs/gdf/lib/libucp.so.0(ucp_worker_progress+0x5a) [0x7f2e437ae8da]
11  /opt/conda/envs/gdf/lib/python3.9/site-packages/ucp/_libs/ucx_api.cpython-39-x86_64-linux-gnu.so(+0x3206a) [0x7f2e4386706a]
12  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x37cb) [0x55cc92af06fb]
13  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x55cc92aec094]
14  /opt/conda/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd9) [0x55cc92afd519]
15  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55cc92aed5c6]
16  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55cc92afd7c2]
17  /opt/conda/envs/gdf/bin/python(+0x14de83) [0x55cc92b0ae83]
18  /opt/conda/envs/gdf/bin/python(+0x258b2c) [0x55cc92c15b2c]
19  /opt/conda/envs/gdf/bin/python(+0xead05) [0x55cc92aa7d05]
20  /opt/conda/envs/gdf/bin/python(+0x1377f3) [0x55cc92af47f3]
21  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x59f9) [0x55cc92af2929]
22  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55cc92afd7c2]
23  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55cc92aed5c6]
24  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55cc92afd7c2]
25  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55cc92aed5c6]
26  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55cc92afd7c2]
27  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55cc92aed5c6]
28  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55cc92afd7c2]
29  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55cc92aed5c6]
30  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x55cc92aec094]
31  /opt/conda/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd9) [0x55cc92afd519]
32  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x11f8) [0x55cc92aee128]
33  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x55cc92aec094]
34  /opt/conda/envs/gdf/bin/python(+0x14dccb) [0x55cc92b0accb]
35  /opt/conda/envs/gdf/bin/python(PyObject_Call+0xbc) [0x55cc92b0b44c]
36  /opt/conda/envs/gdf/bin/python(+0x21110e) [0x55cc92bce10e]
37  /opt/conda/envs/gdf/bin/python(_PyObject_MakeTpCall+0x2ec) [0x55cc92af577c]
38  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x37cb) [0x55cc92af06fb]
39  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55cc92afd7c2]
40  /opt/conda/envs/gdf/bin/python(+0x14ddac) [0x55cc92b0adac]
41  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x37cb) [0x55cc92af06fb]
42  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55cc92afd7c2]
43  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55cc92aed5c6]
44  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x55cc92aec094]
45  /opt/conda/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd9) [0x55cc92afd519]
46  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55cc92aed5c6]
47  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55cc92afd7c2]
48  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x3e2) [0x55cc92aed312]
49  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x55cc92aec094]
50  /opt/conda/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd9) [0x55cc92afd519]
51  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x11f8) [0x55cc92aee128]
52  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x55cc92aec094]
53  /opt/conda/envs/gdf/bin/python(_PyEval_EvalCodeWithName+0x48) [0x55cc92aebd68]
54  /opt/conda/envs/gdf/bin/python(PyEval_EvalCodeEx+0x39) [0x55cc92aebd19]
55  /opt/conda/envs/gdf/bin/python(PyEval_EvalCode+0x1b) [0x55cc92b9907b]
56  /opt/conda/envs/gdf/bin/python(+0x208fca) [0x55cc92bc5fca]
57  /opt/conda/envs/gdf/bin/python(+0x205353) [0x55cc92bc2353]
58  /opt/conda/envs/gdf/bin/python(PyRun_StringFlags+0x9a) [0x55cc92bba16a]
59  /opt/conda/envs/gdf/bin/python(PyRun_SimpleStringFlags+0x3c) [0x55cc92bba05c]
60  /opt/conda/envs/gdf/bin/python(Py_RunMain+0x267) [0x55cc92bb9297]
61  /opt/conda/envs/gdf/bin/python(Py_BytesMain+0x37) [0x55cc92b8cf07]
=================================
[dgx13:83596:0:83596] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x448)
[dgx13:83590:0:83590] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x448)
==== backtrace (tid:  83596) ====
 0  /opt/conda/envs/gdf/lib/libucs.so.0(ucs_handle_error+0x2fd) [0x7f7e5917207d]
 1  /opt/conda/envs/gdf/lib/libucs.so.0(+0x2a274) [0x7f7e59172274]
 2  /opt/conda/envs/gdf/lib/libucs.so.0(+0x2a43a) [0x7f7e5917243a]
 3  /usr/lib/x86_64-linux-gnu/libpthread.so.0(+0x14420) [0x7f7efe4fd420]
 4  /opt/conda/envs/gdf/lib/libucp.so.0(ucp_mem_type_unpack+0x14) [0x7f7e591f16b4]
 5  /opt/conda/envs/gdf/lib/libucp.so.0(ucp_rndv_data_handler+0x4e9) [0x7f7e5921a839]
 6  /opt/conda/envs/gdf/lib/libuct.so.0(+0x203df) [0x7f7e5912c3df]
 7  /opt/conda/envs/gdf/lib/libuct.so.0(+0x23838) [0x7f7e5912f838]
 8  /opt/conda/envs/gdf/lib/libucs.so.0(ucs_event_set_wait+0xb9) [0x7f7e5917b4a9]
 9  /opt/conda/envs/gdf/lib/libuct.so.0(uct_tcp_iface_progress+0x7d) [0x7f7e5912e5dd]
10  /opt/conda/envs/gdf/lib/libucp.so.0(ucp_worker_progress+0x5a) [0x7f7e591ee8da]
11  /opt/conda/envs/gdf/lib/python3.9/site-packages/ucp/_libs/ucx_api.cpython-39-x86_64-linux-gnu.so(+0x3206a) [0x7f7e592a706a]
12  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x37cb) [0x55609a29f6fb]
13  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x55609a29b094]
14  /opt/conda/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd9) [0x55609a2ac519]
15  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55609a29c5c6]
16  /opt/conda/envs/gdf/bin/python(+0x1e3162) [0x55609a34f162]
17  /opt/conda/envs/gdf/lib/python3.9/lib-dynload/_asyncio.cpython-39-x86_64-linux-gnu.so(+0x81e9) [0x7f7ef451f1e9]
18  /opt/conda/envs/gdf/bin/python(_PyObject_MakeTpCall+0x2ec) [0x55609a2a477c]
19  /opt/conda/envs/gdf/bin/python(+0xead05) [0x55609a256d05]
20  /opt/conda/envs/gdf/bin/python(+0x1377f3) [0x55609a2a37f3]
21  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x59f9) [0x55609a2a1929]
22  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55609a2ac7c2]
23  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55609a29c5c6]
24  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55609a2ac7c2]
25  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55609a29c5c6]
26  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55609a2ac7c2]
27  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55609a29c5c6]
28  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55609a2ac7c2]
29  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55609a29c5c6]
30  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x55609a29b094]
31  /opt/conda/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd9) [0x55609a2ac519]
32  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x11f8) [0x55609a29d128]
33  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x55609a29b094]
34  /opt/conda/envs/gdf/bin/python(+0x14dccb) [0x55609a2b9ccb]
35  /opt/conda/envs/gdf/bin/python(PyObject_Call+0xbc) [0x55609a2ba44c]
36  /opt/conda/envs/gdf/bin/python(+0x21110e) [0x55609a37d10e]
37  /opt/conda/envs/gdf/bin/python(_PyObject_MakeTpCall+0x2ec) [0x55609a2a477c]
38  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x37cb) [0x55609a29f6fb]
39  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55609a2ac7c2]
40  /opt/conda/envs/gdf/bin/python(+0x14ddac) [0x55609a2b9dac]
41  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x37cb) [0x55609a29f6fb]
42  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55609a2ac7c2]
43  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55609a29c5c6]
44  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x55609a29b094]
45  /opt/conda/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd9) [0x55609a2ac519]
46  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55609a29c5c6]
47  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55609a2ac7c2]
48  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x3e2) [0x55609a29c312]
49  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x55609a29b094]
50  /opt/conda/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd9) [0x55609a2ac519]
51  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x11f8) [0x55609a29d128]
52  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x55609a29b094]
53  /opt/conda/envs/gdf/bin/python(_PyEval_EvalCodeWithName+0x48) [0x55609a29ad68]
54  /opt/conda/envs/gdf/bin/python(PyEval_EvalCodeEx+0x39) [0x55609a29ad19]
55  /opt/conda/envs/gdf/bin/python(PyEval_EvalCode+0x1b) [0x55609a34807b]
56  /opt/conda/envs/gdf/bin/python(+0x208fca) [0x55609a374fca]
57  /opt/conda/envs/gdf/bin/python(+0x205353) [0x55609a371353]
58  /opt/conda/envs/gdf/bin/python(PyRun_StringFlags+0x9a) [0x55609a36916a]
59  /opt/conda/envs/gdf/bin/python(PyRun_SimpleStringFlags+0x3c) [0x55609a36905c]
60  /opt/conda/envs/gdf/bin/python(Py_RunMain+0x267) [0x55609a368297]
61  /opt/conda/envs/gdf/bin/python(Py_BytesMain+0x37) [0x55609a33bf07]
=================================
==== backtrace (tid:  83590) ====
 0  /opt/conda/envs/gdf/lib/libucs.so.0(ucs_handle_error+0x2fd) [0x7fe2c348607d]
 1  /opt/conda/envs/gdf/lib/libucs.so.0(+0x2a274) [0x7fe2c3486274]
 2  /opt/conda/envs/gdf/lib/libucs.so.0(+0x2a43a) [0x7fe2c348643a]
 3  /usr/lib/x86_64-linux-gnu/libpthread.so.0(+0x14420) [0x7fe368804420]
 4  /opt/conda/envs/gdf/lib/libucp.so.0(ucp_mem_type_unpack+0x14) [0x7fe2c35056b4]
 5  /opt/conda/envs/gdf/lib/libucp.so.0(ucp_rndv_data_handler+0x4e9) [0x7fe2c352e839]
 6  /opt/conda/envs/gdf/lib/libuct.so.0(+0x203df) [0x7fe2c34403df]
 7  /opt/conda/envs/gdf/lib/libuct.so.0(+0x23838) [0x7fe2c3443838]
 8  /opt/conda/envs/gdf/lib/libucs.so.0(ucs_event_set_wait+0xb9) [0x7fe2c348f4a9]
 9  /opt/conda/envs/gdf/lib/libuct.so.0(uct_tcp_iface_progress+0x7d) [0x7fe2c34425dd]
10  /opt/conda/envs/gdf/lib/libucp.so.0(ucp_worker_progress+0x5a) [0x7fe2c35028da]
11  /opt/conda/envs/gdf/lib/python3.9/site-packages/ucp/_libs/ucx_api.cpython-39-x86_64-linux-gnu.so(+0x3206a) [0x7fe2c35bb06a]
12  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x37cb) [0x55bef54916fb]
13  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x55bef548d094]
14  /opt/conda/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd9) [0x55bef549e519]
15  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55bef548e5c6]
16  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55bef549e7c2]
17  /opt/conda/envs/gdf/bin/python(+0x14de83) [0x55bef54abe83]
18  /opt/conda/envs/gdf/bin/python(+0x258b2c) [0x55bef55b6b2c]
19  /opt/conda/envs/gdf/bin/python(+0xead05) [0x55bef5448d05]
20  /opt/conda/envs/gdf/bin/python(+0x1377f3) [0x55bef54957f3]
21  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x59f9) [0x55bef5493929]
22  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55bef549e7c2]
23  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55bef548e5c6]
24  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55bef549e7c2]
25  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55bef548e5c6]
26  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55bef549e7c2]
27  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55bef548e5c6]
28  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55bef549e7c2]
29  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55bef548e5c6]
30  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x55bef548d094]
31  /opt/conda/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd9) [0x55bef549e519]
32  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x11f8) [0x55bef548f128]
33  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x55bef548d094]
34  /opt/conda/envs/gdf/bin/python(+0x14dccb) [0x55bef54abccb]
35  /opt/conda/envs/gdf/bin/python(PyObject_Call+0xbc) [0x55bef54ac44c]
36  /opt/conda/envs/gdf/bin/python(+0x21110e) [0x55bef556f10e]
37  /opt/conda/envs/gdf/bin/python(_PyObject_MakeTpCall+0x2ec) [0x55bef549677c]
38  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x37cb) [0x55bef54916fb]
39  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55bef549e7c2]
40  /opt/conda/envs/gdf/bin/python(+0x14ddac) [0x55bef54abdac]
41  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x37cb) [0x55bef54916fb]
42  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55bef549e7c2]
43  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55bef548e5c6]
44  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x55bef548d094]
45  /opt/conda/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd9) [0x55bef549e519]
46  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55bef548e5c6]
47  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55bef549e7c2]
48  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x3e2) [0x55bef548e312]
49  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x55bef548d094]
50  /opt/conda/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd9) [0x55bef549e519]
51  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x11f8) [0x55bef548f128]
52  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x55bef548d094]
53  /opt/conda/envs/gdf/bin/python(_PyEval_EvalCodeWithName+0x48) [0x55bef548cd68]
54  /opt/conda/envs/gdf/bin/python(PyEval_EvalCodeEx+0x39) [0x55bef548cd19]
55  /opt/conda/envs/gdf/bin/python(PyEval_EvalCode+0x1b) [0x55bef553a07b]
56  /opt/conda/envs/gdf/bin/python(+0x208fca) [0x55bef5566fca]
57  /opt/conda/envs/gdf/bin/python(+0x205353) [0x55bef5563353]
58  /opt/conda/envs/gdf/bin/python(PyRun_StringFlags+0x9a) [0x55bef555b16a]
59  /opt/conda/envs/gdf/bin/python(PyRun_SimpleStringFlags+0x3c) [0x55bef555b05c]
60  /opt/conda/envs/gdf/bin/python(Py_RunMain+0x267) [0x55bef555a297]
61  /opt/conda/envs/gdf/bin/python(Py_BytesMain+0x37) [0x55bef552df07]
=================================
[dgx13:83593:0:83593] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x448)
==== backtrace (tid:  83593) ====
 0  /opt/conda/envs/gdf/lib/libucs.so.0(ucs_handle_error+0x2fd) [0x7f248438707d]
 1  /opt/conda/envs/gdf/lib/libucs.so.0(+0x2a274) [0x7f2484387274]
 2  /opt/conda/envs/gdf/lib/libucs.so.0(+0x2a43a) [0x7f248438743a]
 3  /usr/lib/x86_64-linux-gnu/libpthread.so.0(+0x14420) [0x7f25176f0420]
 4  /opt/conda/envs/gdf/lib/libucp.so.0(ucp_mem_type_unpack+0x14) [0x7f24844066b4]
 5  /opt/conda/envs/gdf/lib/libucp.so.0(ucp_rndv_data_handler+0x4e9) [0x7f248442f839]
 6  /opt/conda/envs/gdf/lib/libuct.so.0(+0x203df) [0x7f24843413df]
 7  /opt/conda/envs/gdf/lib/libuct.so.0(+0x23838) [0x7f2484344838]
 8  /opt/conda/envs/gdf/lib/libucs.so.0(ucs_event_set_wait+0xb9) [0x7f24843904a9]
 9  /opt/conda/envs/gdf/lib/libuct.so.0(uct_tcp_iface_progress+0x7d) [0x7f24843435dd]
10  /opt/conda/envs/gdf/lib/libucp.so.0(ucp_worker_progress+0x5a) [0x7f24844038da]
11  /opt/conda/envs/gdf/lib/python3.9/site-packages/ucp/_libs/ucx_api.cpython-39-x86_64-linux-gnu.so(+0x3206a) [0x7f24844bc06a]
12  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x37cb) [0x55f666f286fb]
13  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x55f666f24094]
14  /opt/conda/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd9) [0x55f666f35519]
15  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55f666f255c6]
16  /opt/conda/envs/gdf/bin/python(+0x1e3162) [0x55f666fd8162]
17  /opt/conda/envs/gdf/lib/python3.9/lib-dynload/_asyncio.cpython-39-x86_64-linux-gnu.so(+0x81e9) [0x7f250d71f1e9]
18  /opt/conda/envs/gdf/bin/python(_PyObject_MakeTpCall+0x2ec) [0x55f666f2d77c]
19  /opt/conda/envs/gdf/bin/python(+0xead05) [0x55f666edfd05]
20  /opt/conda/envs/gdf/bin/python(+0x1377f3) [0x55f666f2c7f3]
21  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x59f9) [0x55f666f2a929]
22  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55f666f357c2]
23  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55f666f255c6]
24  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55f666f357c2]
25  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55f666f255c6]
26  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55f666f357c2]
27  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55f666f255c6]
28  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55f666f357c2]
29  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55f666f255c6]
30  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x55f666f24094]
31  /opt/conda/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd9) [0x55f666f35519]
32  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x11f8) [0x55f666f26128]
33  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x55f666f24094]
34  /opt/conda/envs/gdf/bin/python(+0x14dccb) [0x55f666f42ccb]
35  /opt/conda/envs/gdf/bin/python(PyObject_Call+0xbc) [0x55f666f4344c]
36  /opt/conda/envs/gdf/bin/python(+0x21110e) [0x55f66700610e]
37  /opt/conda/envs/gdf/bin/python(_PyObject_MakeTpCall+0x2ec) [0x55f666f2d77c]
38  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x37cb) [0x55f666f286fb]
39  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55f666f357c2]
40  /opt/conda/envs/gdf/bin/python(+0x14ddac) [0x55f666f42dac]
41  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x37cb) [0x55f666f286fb]
42  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55f666f357c2]
43  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55f666f255c6]
44  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x55f666f24094]
45  /opt/conda/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd9) [0x55f666f35519]
46  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55f666f255c6]
47  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55f666f357c2]
48  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x3e2) [0x55f666f25312]
49  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x55f666f24094]
50  /opt/conda/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd9) [0x55f666f35519]
51  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x11f8) [0x55f666f26128]
52  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x55f666f24094]
53  /opt/conda/envs/gdf/bin/python(_PyEval_EvalCodeWithName+0x48) [0x55f666f23d68]
54  /opt/conda/envs/gdf/bin/python(PyEval_EvalCodeEx+0x39) [0x55f666f23d19]
55  /opt/conda/envs/gdf/bin/python(PyEval_EvalCode+0x1b) [0x55f666fd107b]
56  /opt/conda/envs/gdf/bin/python(+0x208fca) [0x55f666ffdfca]
57  /opt/conda/envs/gdf/bin/python(+0x205353) [0x55f666ffa353]
58  /opt/conda/envs/gdf/bin/python(PyRun_StringFlags+0x9a) [0x55f666ff216a]
59  /opt/conda/envs/gdf/bin/python(PyRun_SimpleStringFlags+0x3c) [0x55f666ff205c]
60  /opt/conda/envs/gdf/bin/python(Py_RunMain+0x267) [0x55f666ff1297]
61  /opt/conda/envs/gdf/bin/python(Py_BytesMain+0x37) [0x55f666fc4f07]
=================================
2023-11-15 08:56:52,673 - distributed.worker - ERROR - failed during get data with ucx://127.0.0.1:32997 -> ucx://127.0.0.1:44785
Traceback (most recent call last):
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 338, in write
    await self.ep.send(each_frame)
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/ucp/core.py", line 650, in send
    return await comm.tag_send(self._ep, buffer, nbytes, tag, name=log)
ucp._libs.exceptions.UCXError: <[Send #007] ep: 0x7f6fc86f42c0, tag: 0xae70a2779dc8119a, nbytes: 50000000, type: <class 'cupy.ndarray'>>: Connection reset by remote peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/worker.py", line 1782, in get_data
    compressed = await comm.write(msg, serializers=serializers)
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/utils.py", line 803, in wrapper
    return await func(*args, **kwargs)
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 342, in write
    raise CommClosedError("While writing, the connection was closed")
distributed.comm.core.CommClosedError: While writing, the connection was closed
Task exception was never retrieved
future: <Task finished name='Task-357' coro=<_listener_handler_coroutine() done, defined at /opt/conda/envs/gdf/lib/python3.9/site-packages/ucp/core.py:128> exception=UCXError('<stream_send>: Connection reset by remote peer')>
Traceback (most recent call last):
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/ucp/core.py", line 143, in _listener_handler_coroutine
    peer_info = await exchange_peer_info(
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/ucp/core.py", line 51, in exchange_peer_info
    await comm.stream_send(endpoint, my_info_arr, my_info_arr.nbytes)
ucp._libs.exceptions.UCXError: <stream_send>: Connection reset by remote peer
2023-11-15 08:56:52,678 - distributed.worker - ERROR - Worker stream died during communication: ucx://127.0.0.1:44785
Traceback (most recent call last):
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 471, in connect
    ep = await ucp.create_endpoint(ip, port)
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/ucp/core.py", line 1004, in create_endpoint
    return await _get_ctx().create_endpoint(
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/ucp/core.py", line 316, in create_endpoint
    peer_info = await exchange_peer_info(
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/ucp/core.py", line 54, in exchange_peer_info
    await comm.stream_recv(endpoint, peer_info_arr, peer_info_arr.nbytes)
ucp._libs.exceptions.UCXError: <stream_recv>: Connection reset by remote peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/comm/core.py", line 342, in connect
    comm = await wait_for(
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/utils.py", line 1920, in wait_for
    return await asyncio.wait_for(fut, timeout)
  File "/opt/conda/envs/gdf/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 473, in connect
    raise CommClosedError("Connection closed before handshake completed")
distributed.comm.core.CommClosedError: Connection closed before handshake completed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/core.py", line 1516, in _connect
    comm = await connect(
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/comm/core.py", line 366, in connect
    await asyncio.sleep(backoff)
  File "/opt/conda/envs/gdf/lib/python3.9/asyncio/tasks.py", line 652, in sleep
    return await future
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/core.py", line 1626, in connect
    return connect_attempt.result()
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/worker.py", line 2059, in gather_dep
    response = await get_data_from_worker(
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/worker.py", line 2849, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/core.py", line 1628, in connect
    raise CommClosedError(reason)
distributed.comm.core.CommClosedError: Address removed.
2023-11-15 08:56:53,021 - distributed.worker - ERROR - failed during get data with ucx://127.0.0.1:32997 -> ucx://127.0.0.1:43935
Traceback (most recent call last):
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 338, in write
    await self.ep.send(each_frame)
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/ucp/core.py", line 650, in send
    return await comm.tag_send(self._ep, buffer, nbytes, tag, name=log)
ucp._libs.exceptions.UCXError: <[Send #007] ep: 0x7f6fc86f4180, tag: 0x5f18932bff467d4f, nbytes: 50000000, type: <class 'cupy.ndarray'>>: Connection reset by remote peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/worker.py", line 1782, in get_data
    compressed = await comm.write(msg, serializers=serializers)
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/utils.py", line 803, in wrapper
    return await func(*args, **kwargs)
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 342, in write
    raise CommClosedError("While writing, the connection was closed")
distributed.comm.core.CommClosedError: While writing, the connection was closed
2023-11-15 08:56:53,021 - distributed.worker - ERROR - failed during get data with ucx://127.0.0.1:50427 -> ucx://127.0.0.1:43935
Traceback (most recent call last):
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 338, in write
    await self.ep.send(each_frame)
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/ucp/core.py", line 650, in send
    return await comm.tag_send(self._ep, buffer, nbytes, tag, name=log)
ucp._libs.exceptions.UCXError: <[Send #007] ep: 0x7f00c176f340, tag: 0xd3f0f4958910850b, nbytes: 50000000, type: <class 'cupy.ndarray'>>: Connection reset by remote peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/worker.py", line 1782, in get_data
    compressed = await comm.write(msg, serializers=serializers)
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/utils.py", line 803, in wrapper
    return await func(*args, **kwargs)
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 342, in write
    raise CommClosedError("While writing, the connection was closed")
distributed.comm.core.CommClosedError: While writing, the connection was closed
2023-11-15 08:56:53,022 - distributed.worker - ERROR - Worker stream died during communication: ucx://127.0.0.1:43935
Traceback (most recent call last):
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 396, in read
    await self.ep.recv(each_frame)
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/ucp/core.py", line 725, in recv
    ret = await comm.tag_recv(self._ep, buffer, nbytes, tag, name=log)
ucp._libs.exceptions.UCXError: <[Recv #007] ep: 0x7f6fc86f41c0, tag: 0x2b9a9c742ae5e864, nbytes: 50000000, type: <class 'rmm._lib.device_buffer.DeviceBuffer'>>: Connection reset by remote peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/worker.py", line 2059, in gather_dep
    response = await get_data_from_worker(
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/worker.py", line 2852, in get_data_from_worker
    response = await send_recv(
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/core.py", line 1106, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/utils.py", line 803, in wrapper
    return await func(*args, **kwargs)
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 402, in read
    raise CommClosedError(
distributed.comm.core.CommClosedError: Connection closed by writer.
Inner exception: UCXError("<[Recv #007] ep: 0x7f6fc86f41c0, tag: 0x2b9a9c742ae5e864, nbytes: 50000000, type: <class 'rmm._lib.device_buffer.DeviceBuffer'>>: Connection reset by remote peer")
2023-11-15 08:56:53,022 - distributed.worker - ERROR - Worker stream died during communication: ucx://127.0.0.1:53763
Traceback (most recent call last):
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 396, in read
    await self.ep.recv(each_frame)
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/ucp/core.py", line 725, in recv
    ret = await comm.tag_recv(self._ep, buffer, nbytes, tag, name=log)
ucp._libs.exceptions.UCXError: <[Recv #007] ep: 0x7f00c176f180, tag: 0xb75d784259919854, nbytes: 50000000, type: <class 'rmm._lib.device_buffer.DeviceBuffer'>>: Connection reset by remote peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/worker.py", line 2059, in gather_dep
    response = await get_data_from_worker(
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/worker.py", line 2852, in get_data_from_worker
    response = await send_recv(
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/core.py", line 1106, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/utils.py", line 803, in wrapper
    return await func(*args, **kwargs)
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 402, in read
    raise CommClosedError(
distributed.comm.core.CommClosedError: Connection closed by writer.
Inner exception: UCXError("<[Recv #007] ep: 0x7f00c176f180, tag: 0xb75d784259919854, nbytes: 50000000, type: <class 'rmm._lib.device_buffer.DeviceBuffer'>>: Connection reset by remote peer")
2023-11-15 08:56:53,023 - distributed.worker - ERROR - failed during get data with ucx://127.0.0.1:50427 -> ucx://127.0.0.1:53763
Traceback (most recent call last):
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 338, in write
    await self.ep.send(each_frame)
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/ucp/core.py", line 650, in send
    return await comm.tag_send(self._ep, buffer, nbytes, tag, name=log)
ucp._libs.exceptions.UCXError: <[Send #007] ep: 0x7f00c176f3c0, tag: 0xbaaac4fd3092f303, nbytes: 50000000, type: <class 'cupy.ndarray'>>: Connection reset by remote peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/worker.py", line 1782, in get_data
    compressed = await comm.write(msg, serializers=serializers)
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/utils.py", line 803, in wrapper
    return await func(*args, **kwargs)
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 342, in write
    raise CommClosedError("While writing, the connection was closed")
distributed.comm.core.CommClosedError: While writing, the connection was closed
2023-11-15 08:56:53,029 - distributed.worker - ERROR - Worker stream died during communication: ucx://127.0.0.1:43667
Traceback (most recent call last):
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 396, in read
    await self.ep.recv(each_frame)
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/ucp/core.py", line 725, in recv
    ret = await comm.tag_recv(self._ep, buffer, nbytes, tag, name=log)
ucp._libs.exceptions.UCXError: <[Recv #007] ep: 0x7f00c176f240, tag: 0x785f6c97b2ba7d0a, nbytes: 50000000, type: <class 'rmm._lib.device_buffer.DeviceBuffer'>>: Connection reset by remote peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/worker.py", line 2059, in gather_dep
    response = await get_data_from_worker(
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/worker.py", line 2852, in get_data_from_worker
    response = await send_recv(
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/core.py", line 1106, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/utils.py", line 803, in wrapper
    return await func(*args, **kwargs)
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 402, in read
    raise CommClosedError(
distributed.comm.core.CommClosedError: Connection closed by writer.
Inner exception: UCXError("<[Recv #007] ep: 0x7f00c176f240, tag: 0x785f6c97b2ba7d0a, nbytes: 50000000, type: <class 'rmm._lib.device_buffer.DeviceBuffer'>>: Connection reset by remote peer")
2023-11-15 08:56:53,029 - distributed.worker - ERROR - failed during get data with ucx://127.0.0.1:32997 -> ucx://127.0.0.1:43667
Traceback (most recent call last):
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 338, in write
    await self.ep.send(each_frame)
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/ucp/core.py", line 650, in send
    return await comm.tag_send(self._ep, buffer, nbytes, tag, name=log)
ucp._libs.exceptions.UCXError: <[Send #007] ep: 0x7f6fc86f4140, tag: 0x50167fe59754a16c, nbytes: 50000000, type: <class 'cupy.ndarray'>>: Connection reset by remote peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/worker.py", line 1782, in get_data
    compressed = await comm.write(msg, serializers=serializers)
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/utils.py", line 803, in wrapper
    return await func(*args, **kwargs)
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 342, in write
    raise CommClosedError("While writing, the connection was closed")
distributed.comm.core.CommClosedError: While writing, the connection was closed
2023-11-15 08:56:53,033 - distributed.worker - ERROR - Worker stream died during communication: ucx://127.0.0.1:43667
Traceback (most recent call last):
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 354, in read
    await self.ep.recv(msg)
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/ucp/core.py", line 725, in recv
    ret = await comm.tag_recv(self._ep, buffer, nbytes, tag, name=log)
ucp._libs.exceptions.UCXCanceled: <[Recv #003] ep: 0x7f6fc86f4280, tag: 0x5f272f7caf335f34, nbytes: 16, type: <class 'numpy.ndarray'>>: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/worker.py", line 2059, in gather_dep
    response = await get_data_from_worker(
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/worker.py", line 2852, in get_data_from_worker
    response = await send_recv(
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/core.py", line 1106, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/utils.py", line 803, in wrapper
    return await func(*args, **kwargs)
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 372, in read
    raise CommClosedError(
distributed.comm.core.CommClosedError: Connection closed by writer.
Inner exception: UCXCanceled("<[Recv #003] ep: 0x7f6fc86f4280, tag: 0x5f272f7caf335f34, nbytes: 16, type: <class 'numpy.ndarray'>>: ")
2023-11-15 08:56:59,694 - distributed.nanny - WARNING - Restarting worker
2023-11-15 08:56:59,734 - distributed.nanny - WARNING - Restarting worker
2023-11-15 08:57:00,137 - distributed.nanny - WARNING - Restarting worker
2023-11-15 08:57:00,401 - distributed.nanny - WARNING - Restarting worker
2023-11-15 08:57:00,548 - distributed.nanny - WARNING - Restarting worker
2023-11-15 08:57:00,549 - distributed.nanny - WARNING - Restarting worker
[dgx13:83747:0:83747] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x448)
==== backtrace (tid:  83747) ====
 0  /opt/conda/envs/gdf/lib/libucs.so.0(ucs_handle_error+0x2fd) [0x7fe2c8ce507d]
 1  /opt/conda/envs/gdf/lib/libucs.so.0(+0x2a274) [0x7fe2c8ce5274]
 2  /opt/conda/envs/gdf/lib/libucs.so.0(+0x2a43a) [0x7fe2c8ce543a]
 3  /usr/lib/x86_64-linux-gnu/libpthread.so.0(+0x14420) [0x7fe35bf08420]
 4  /opt/conda/envs/gdf/lib/libucp.so.0(ucp_mem_type_unpack+0x14) [0x7fe2c8d646b4]
 5  /opt/conda/envs/gdf/lib/libucp.so.0(ucp_rndv_data_handler+0x4e9) [0x7fe2c8d8d839]
 6  /opt/conda/envs/gdf/lib/libuct.so.0(+0x203df) [0x7fe2c8c9f3df]
 7  /opt/conda/envs/gdf/lib/libuct.so.0(+0x23838) [0x7fe2c8ca2838]
 8  /opt/conda/envs/gdf/lib/libucs.so.0(ucs_event_set_wait+0xb9) [0x7fe2c8cee4a9]
 9  /opt/conda/envs/gdf/lib/libuct.so.0(uct_tcp_iface_progress+0x7d) [0x7fe2c8ca15dd]
10  /opt/conda/envs/gdf/lib/libucp.so.0(ucp_worker_progress+0x5a) [0x7fe2c8d618da]
11  /opt/conda/envs/gdf/lib/python3.9/site-packages/ucp/_libs/ucx_api.cpython-39-x86_64-linux-gnu.so(+0x3206a) [0x7fe2c8e1a06a]
12  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x37cb) [0x555b328126fb]
13  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x555b3280e094]
14  /opt/conda/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd9) [0x555b3281f519]
15  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x555b3280f5c6]
16  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x555b3281f7c2]
17  /opt/conda/envs/gdf/bin/python(+0x14de83) [0x555b3282ce83]
18  /opt/conda/envs/gdf/bin/python(+0x258b2c) [0x555b32937b2c]
19  /opt/conda/envs/gdf/bin/python(+0xead05) [0x555b327c9d05]
20  /opt/conda/envs/gdf/bin/python(+0x1377f3) [0x555b328167f3]
21  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x59f9) [0x555b32814929]
22  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x555b3281f7c2]
23  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x555b3280f5c6]
24  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x555b3281f7c2]
25  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x555b3280f5c6]
26  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x555b3281f7c2]
27  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x555b3280f5c6]
28  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x555b3281f7c2]
29  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x555b3280f5c6]
30  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x555b3280e094]
31  /opt/conda/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd9) [0x555b3281f519]
32  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x11f8) [0x555b32810128]
33  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x555b3280e094]
34  /opt/conda/envs/gdf/bin/python(+0x14dccb) [0x555b3282cccb]
35  /opt/conda/envs/gdf/bin/python(PyObject_Call+0xbc) [0x555b3282d44c]
36  /opt/conda/envs/gdf/bin/python(+0x21110e) [0x555b328f010e]
37  /opt/conda/envs/gdf/bin/python(_PyObject_MakeTpCall+0x2ec) [0x555b3281777c]
38  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x37cb) [0x555b328126fb]
39  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x555b3281f7c2]
40  /opt/conda/envs/gdf/bin/python(+0x14ddac) [0x555b3282cdac]
41  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x37cb) [0x555b328126fb]
42  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x555b3281f7c2]
43  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x555b3280f5c6]
44  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x555b3280e094]
45  /opt/conda/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd9) [0x555b3281f519]
46  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x555b3280f5c6]
47  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x555b3281f7c2]
48  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x3e2) [0x555b3280f312]
49  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x555b3280e094]
50  /opt/conda/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd9) [0x555b3281f519]
51  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x11f8) [0x555b32810128]
52  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x555b3280e094]
53  /opt/conda/envs/gdf/bin/python(_PyEval_EvalCodeWithName+0x48) [0x555b3280dd68]
54  /opt/conda/envs/gdf/bin/python(PyEval_EvalCodeEx+0x39) [0x555b3280dd19]
55  /opt/conda/envs/gdf/bin/python(PyEval_EvalCode+0x1b) [0x555b328bb07b]
56  /opt/conda/envs/gdf/bin/python(+0x208fca) [0x555b328e7fca]
57  /opt/conda/envs/gdf/bin/python(+0x205353) [0x555b328e4353]
58  /opt/conda/envs/gdf/bin/python(PyRun_StringFlags+0x9a) [0x555b328dc16a]
59  /opt/conda/envs/gdf/bin/python(PyRun_SimpleStringFlags+0x3c) [0x555b328dc05c]
60  /opt/conda/envs/gdf/bin/python(Py_RunMain+0x267) [0x555b328db297]
61  /opt/conda/envs/gdf/bin/python(Py_BytesMain+0x37) [0x555b328aef07]
=================================
[dgx13:83744:0:83744] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x448)
==== backtrace (tid:  83744) ====
 0  /opt/conda/envs/gdf/lib/libucs.so.0(ucs_handle_error+0x2fd) [0x7fc4e5c4707d]
 1  /opt/conda/envs/gdf/lib/libucs.so.0(+0x2a274) [0x7fc4e5c47274]
 2  /opt/conda/envs/gdf/lib/libucs.so.0(+0x2a43a) [0x7fc4e5c4743a]
 3  /usr/lib/x86_64-linux-gnu/libpthread.so.0(+0x14420) [0x7fc58ce80420]
 4  /opt/conda/envs/gdf/lib/libucp.so.0(ucp_mem_type_unpack+0x14) [0x7fc4e5cc66b4]
 5  /opt/conda/envs/gdf/lib/libucp.so.0(ucp_rndv_data_handler+0x4e9) [0x7fc4e5cef839]
 6  /opt/conda/envs/gdf/lib/libuct.so.0(+0x203df) [0x7fc4e5c013df]
 7  /opt/conda/envs/gdf/lib/libuct.so.0(+0x23838) [0x7fc4e5c04838]
 8  /opt/conda/envs/gdf/lib/libucs.so.0(ucs_event_set_wait+0xb9) [0x7fc4e5c504a9]
 9  /opt/conda/envs/gdf/lib/libuct.so.0(uct_tcp_iface_progress+0x7d) [0x7fc4e5c035dd]
10  /opt/conda/envs/gdf/lib/libucp.so.0(ucp_worker_progress+0x5a) [0x7fc4e5cc38da]
11  /opt/conda/envs/gdf/lib/python3.9/site-packages/ucp/_libs/ucx_api.cpython-39-x86_64-linux-gnu.so(+0x3206a) [0x7fc4e5d7c06a]
12  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x37cb) [0x55a3d546d6fb]
13  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x55a3d5469094]
14  /opt/conda/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd9) [0x55a3d547a519]
15  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55a3d546a5c6]
16  /opt/conda/envs/gdf/bin/python(+0x1e3162) [0x55a3d551d162]
17  /opt/conda/envs/gdf/lib/python3.9/lib-dynload/_asyncio.cpython-39-x86_64-linux-gnu.so(+0x81e9) [0x7fc582e9f1e9]
18  /opt/conda/envs/gdf/bin/python(_PyObject_MakeTpCall+0x2ec) [0x55a3d547277c]
19  /opt/conda/envs/gdf/bin/python(+0xead05) [0x55a3d5424d05]
20  /opt/conda/envs/gdf/bin/python(+0x1377f3) [0x55a3d54717f3]
21  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x59f9) [0x55a3d546f929]
22  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55a3d547a7c2]
23  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55a3d546a5c6]
24  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55a3d547a7c2]
25  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55a3d546a5c6]
26  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55a3d547a7c2]
27  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55a3d546a5c6]
28  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55a3d547a7c2]
29  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55a3d546a5c6]
30  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x55a3d5469094]
31  /opt/conda/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd9) [0x55a3d547a519]
32  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x11f8) [0x55a3d546b128]
33  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x55a3d5469094]
34  /opt/conda/envs/gdf/bin/python(+0x14dccb) [0x55a3d5487ccb]
35  /opt/conda/envs/gdf/bin/python(PyObject_Call+0xbc) [0x55a3d548844c]
36  /opt/conda/envs/gdf/bin/python(+0x21110e) [0x55a3d554b10e]
37  /opt/conda/envs/gdf/bin/python(_PyObject_MakeTpCall+0x2ec) [0x55a3d547277c]
38  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x37cb) [0x55a3d546d6fb]
39  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55a3d547a7c2]
40  /opt/conda/envs/gdf/bin/python(+0x14ddac) [0x55a3d5487dac]
41  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x37cb) [0x55a3d546d6fb]
42  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55a3d547a7c2]
43  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55a3d546a5c6]
44  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x55a3d5469094]
45  /opt/conda/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd9) [0x55a3d547a519]
46  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x55a3d546a5c6]
47  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x55a3d547a7c2]
48  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x3e2) [0x55a3d546a312]
49  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x55a3d5469094]
50  /opt/conda/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd9) [0x55a3d547a519]
51  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x11f8) [0x55a3d546b128]
52  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x55a3d5469094]
53  /opt/conda/envs/gdf/bin/python(_PyEval_EvalCodeWithName+0x48) [0x55a3d5468d68]
54  /opt/conda/envs/gdf/bin/python(PyEval_EvalCodeEx+0x39) [0x55a3d5468d19]
55  /opt/conda/envs/gdf/bin/python(PyEval_EvalCode+0x1b) [0x55a3d551607b]
56  /opt/conda/envs/gdf/bin/python(+0x208fca) [0x55a3d5542fca]
57  /opt/conda/envs/gdf/bin/python(+0x205353) [0x55a3d553f353]
58  /opt/conda/envs/gdf/bin/python(PyRun_StringFlags+0x9a) [0x55a3d553716a]
59  /opt/conda/envs/gdf/bin/python(PyRun_SimpleStringFlags+0x3c) [0x55a3d553705c]
60  /opt/conda/envs/gdf/bin/python(Py_RunMain+0x267) [0x55a3d5536297]
61  /opt/conda/envs/gdf/bin/python(Py_BytesMain+0x37) [0x55a3d5509f07]
=================================
2023-11-15 08:57:05,170 - distributed.worker - ERROR - failed during get data with ucx://127.0.0.1:50427 -> ucx://127.0.0.1:36059
Traceback (most recent call last):
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 338, in write
    await self.ep.send(each_frame)
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/ucp/core.py", line 650, in send
    return await comm.tag_send(self._ep, buffer, nbytes, tag, name=log)
ucp._libs.exceptions.UCXError: <[Send #007] ep: 0x7f00c176f240, tag: 0x8742e5e3f7f7c140, nbytes: 50000000, type: <class 'cupy.ndarray'>>: Connection reset by remote peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/worker.py", line 1782, in get_data
    compressed = await comm.write(msg, serializers=serializers)
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/utils.py", line 803, in wrapper
    return await func(*args, **kwargs)
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 342, in write
    raise CommClosedError("While writing, the connection was closed")
distributed.comm.core.CommClosedError: While writing, the connection was closed
2023-11-15 08:57:05,428 - distributed.worker - ERROR - failed during get data with ucx://127.0.0.1:50427 -> ucx://127.0.0.1:57641
Traceback (most recent call last):
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 338, in write
    await self.ep.send(each_frame)
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/ucp/core.py", line 650, in send
    return await comm.tag_send(self._ep, buffer, nbytes, tag, name=log)
ucp._libs.exceptions.UCXError: <[Send #007] ep: 0x7f00c176f180, tag: 0x85959d3a46994930, nbytes: 50000000, type: <class 'cupy.ndarray'>>: Connection reset by remote peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/worker.py", line 1782, in get_data
    compressed = await comm.write(msg, serializers=serializers)
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/utils.py", line 803, in wrapper
    return await func(*args, **kwargs)
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 342, in write
    raise CommClosedError("While writing, the connection was closed")
distributed.comm.core.CommClosedError: While writing, the connection was closed
[dgx13:83741:0:83741] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x448)
==== backtrace (tid:  83741) ====
 0  /opt/conda/envs/gdf/lib/libucs.so.0(ucs_handle_error+0x2fd) [0x7f206802d07d]
 1  /opt/conda/envs/gdf/lib/libucs.so.0(+0x2a274) [0x7f206802d274]
 2  /opt/conda/envs/gdf/lib/libucs.so.0(+0x2a43a) [0x7f206802d43a]
 3  /usr/lib/x86_64-linux-gnu/libpthread.so.0(+0x14420) [0x7f2109189420]
 4  /opt/conda/envs/gdf/lib/libucp.so.0(ucp_mem_type_unpack+0x14) [0x7f2061f7c6b4]
 5  /opt/conda/envs/gdf/lib/libucp.so.0(ucp_rndv_data_handler+0x4e9) [0x7f2061fa5839]
 6  /opt/conda/envs/gdf/lib/libuct.so.0(+0x203df) [0x7f2061f163df]
 7  /opt/conda/envs/gdf/lib/libuct.so.0(+0x23838) [0x7f2061f19838]
 8  /opt/conda/envs/gdf/lib/libucs.so.0(ucs_event_set_wait+0xb9) [0x7f20680364a9]
 9  /opt/conda/envs/gdf/lib/libuct.so.0(uct_tcp_iface_progress+0x7d) [0x7f2061f185dd]
10  /opt/conda/envs/gdf/lib/libucp.so.0(ucp_worker_progress+0x5a) [0x7f2061f798da]
11  /opt/conda/envs/gdf/lib/python3.9/site-packages/ucp/_libs/ucx_api.cpython-39-x86_64-linux-gnu.so(+0x3206a) [0x7f206809406a]
12  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x37cb) [0x56104b7876fb]
13  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x56104b783094]
14  /opt/conda/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd9) [0x56104b794519]
15  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x56104b7845c6]
16  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x56104b7947c2]
17  /opt/conda/envs/gdf/bin/python(+0x14de83) [0x56104b7a1e83]
18  /opt/conda/envs/gdf/bin/python(+0x258b2c) [0x56104b8acb2c]
19  /opt/conda/envs/gdf/bin/python(+0xead05) [0x56104b73ed05]
20  /opt/conda/envs/gdf/bin/python(+0x1377f3) [0x56104b78b7f3]
21  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x59f9) [0x56104b789929]
22  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x56104b7947c2]
23  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x56104b7845c6]
24  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x56104b7947c2]
25  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x56104b7845c6]
26  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x56104b7947c2]
27  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x56104b7845c6]
28  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x56104b7947c2]
29  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x56104b7845c6]
30  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x56104b783094]
31  /opt/conda/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd9) [0x56104b794519]
32  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x11f8) [0x56104b785128]
33  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x56104b783094]
34  /opt/conda/envs/gdf/bin/python(+0x14dccb) [0x56104b7a1ccb]
35  /opt/conda/envs/gdf/bin/python(PyObject_Call+0xbc) [0x56104b7a244c]
36  /opt/conda/envs/gdf/bin/python(+0x21110e) [0x56104b86510e]
37  /opt/conda/envs/gdf/bin/python(_PyObject_MakeTpCall+0x2ec) [0x56104b78c77c]
38  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x37cb) [0x56104b7876fb]
39  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x56104b7947c2]
40  /opt/conda/envs/gdf/bin/python(+0x14ddac) [0x56104b7a1dac]
41  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x37cb) [0x56104b7876fb]
42  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x56104b7947c2]
43  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x56104b7845c6]
44  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x56104b783094]
45  /opt/conda/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd9) [0x56104b794519]
46  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x696) [0x56104b7845c6]
47  /opt/conda/envs/gdf/bin/python(+0x1407c2) [0x56104b7947c2]
48  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x3e2) [0x56104b784312]
49  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x56104b783094]
50  /opt/conda/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd9) [0x56104b794519]
51  /opt/conda/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x11f8) [0x56104b785128]
52  /opt/conda/envs/gdf/bin/python(+0x12f094) [0x56104b783094]
53  /opt/conda/envs/gdf/bin/python(_PyEval_EvalCodeWithName+0x48) [0x56104b782d68]
54  /opt/conda/envs/gdf/bin/python(PyEval_EvalCodeEx+0x39) [0x56104b782d19]
55  /opt/conda/envs/gdf/bin/python(PyEval_EvalCode+0x1b) [0x56104b83007b]
56  /opt/conda/envs/gdf/bin/python(+0x208fca) [0x56104b85cfca]
57  /opt/conda/envs/gdf/bin/python(+0x205353) [0x56104b859353]
58  /opt/conda/envs/gdf/bin/python(PyRun_StringFlags+0x9a) [0x56104b85116a]
59  /opt/conda/envs/gdf/bin/python(PyRun_SimpleStringFlags+0x3c) [0x56104b85105c]
60  /opt/conda/envs/gdf/bin/python(Py_RunMain+0x267) [0x56104b850297]
61  /opt/conda/envs/gdf/bin/python(Py_BytesMain+0x37) [0x56104b823f07]
=================================
2023-11-15 08:57:06,299 - distributed.worker - ERROR - failed during get data with ucx://127.0.0.1:50427 -> ucx://127.0.0.1:41509
Traceback (most recent call last):
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 338, in write
    await self.ep.send(each_frame)
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/ucp/core.py", line 650, in send
    return await comm.tag_send(self._ep, buffer, nbytes, tag, name=log)
ucp._libs.exceptions.UCXError: <[Send #007] ep: 0x7f00c176f180, tag: 0xa37f979981f034a9, nbytes: 50000000, type: <class 'cupy.ndarray'>>: Connection reset by remote peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/worker.py", line 1782, in get_data
    compressed = await comm.write(msg, serializers=serializers)
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/utils.py", line 803, in wrapper
    return await func(*args, **kwargs)
  File "/opt/conda/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 342, in write
    raise CommClosedError("While writing, the connection was closed")
distributed.comm.core.CommClosedError: While writing, the connection was closed
2023-11-15 08:57:07,942 - distributed.nanny - WARNING - Restarting worker
/opt/conda/envs/gdf/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 30 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
