2023-02-08 00:02:10,286 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-02-08 00:02:10,286 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-02-08 00:02:10,326 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-02-08 00:02:10,327 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-02-08 00:02:10,327 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-02-08 00:02:10,327 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-02-08 00:02:10,329 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-02-08 00:02:10,329 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-02-08 00:02:10,340 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-02-08 00:02:10,340 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-02-08 00:02:10,356 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-02-08 00:02:10,356 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-02-08 00:02:10,356 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-02-08 00:02:10,357 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-02-08 00:02:10,381 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-02-08 00:02:10,381 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
[dgx13:61590:0:61590] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x448)
==== backtrace (tid:  61590) ====
 0  /datasets/pentschev/miniconda3/envs/gdf/lib/libucs.so.0(ucs_handle_error+0x2d4) [0x7f808dcf4614]
 1  /datasets/pentschev/miniconda3/envs/gdf/lib/libucs.so.0(+0x2e7ef) [0x7f808dcf47ef]
 2  /datasets/pentschev/miniconda3/envs/gdf/lib/libucs.so.0(+0x2eb14) [0x7f808dcf4b14]
 3  /lib/x86_64-linux-gnu/libpthread.so.0(+0x12980) [0x7f8103539980]
 4  /datasets/pentschev/miniconda3/envs/gdf/lib/libucp.so.0(ucp_mem_type_unpack+0x14) [0x7f808df793b4]
 5  /datasets/pentschev/miniconda3/envs/gdf/lib/libucp.so.0(ucp_rndv_data_handler+0x508) [0x7f808dfa9a08]
 6  /datasets/pentschev/miniconda3/envs/gdf/lib/libuct.so.0(+0x20b5f) [0x7f808daa8b5f]
 7  /datasets/pentschev/miniconda3/envs/gdf/lib/libuct.so.0(+0x21134) [0x7f808daa9134]
 8  /datasets/pentschev/miniconda3/envs/gdf/lib/libuct.so.0(+0x23578) [0x7f808daab578]
 9  /datasets/pentschev/miniconda3/envs/gdf/lib/libucs.so.0(ucs_event_set_wait+0xb9) [0x7f808dcfec99]
10  /datasets/pentschev/miniconda3/envs/gdf/lib/libuct.so.0(uct_tcp_iface_progress+0x7b) [0x7f808daab61b]
11  /datasets/pentschev/miniconda3/envs/gdf/lib/libucp.so.0(ucp_worker_progress+0x6a) [0x7f808df75caa]
12  /datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/ucp/_libs/ucx_api.cpython-39-x86_64-linux-gnu.so(+0x26c79) [0x7f808e22fc79]
13  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x13eb08) [0x559a5649fb08]
14  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x5f82) [0x559a56490112]
15  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x12827a) [0x559a5648927a]
16  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd5) [0x559a5649ac05]
17  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x68b) [0x559a5648a81b]
18  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x139ef3) [0x559a5649aef3]
19  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x147a16) [0x559a564a8a16]
20  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x2579b1) [0x559a565b89b1]
21  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0xe5817) [0x559a56446817]
22  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x130f83) [0x559a56491f83]
23  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x5ba6) [0x559a5648fd36]
24  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x139ef3) [0x559a5649aef3]
25  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x68b) [0x559a5648a81b]
26  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x139ef3) [0x559a5649aef3]
27  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x68b) [0x559a5648a81b]
28  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x139ef3) [0x559a5649aef3]
29  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x68b) [0x559a5648a81b]
30  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x139ef3) [0x559a5649aef3]
31  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x68b) [0x559a5648a81b]
32  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x12827a) [0x559a5648927a]
33  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd5) [0x559a5649ac05]
34  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x4e17) [0x559a5648efa7]
35  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x12827a) [0x559a5648927a]
36  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x147935) [0x559a564a8935]
37  /datasets/pentschev/miniconda3/envs/gdf/bin/python(PyObject_Call+0xb4) [0x559a564a9104]
38  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x20efc8) [0x559a5656ffc8]
39  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyObject_MakeTpCall+0x2fc) [0x559a564932bc]
40  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x402b) [0x559a5648e1bb]
41  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x139ef3) [0x559a5649aef3]
42  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x147c72) [0x559a564a8c72]
43  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x402b) [0x559a5648e1bb]
44  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x139ef3) [0x559a5649aef3]
45  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x68b) [0x559a5648a81b]
46  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x12827a) [0x559a5648927a]
47  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd5) [0x559a5649ac05]
48  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x68b) [0x559a5648a81b]
49  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x139ef3) [0x559a5649aef3]
50  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x3d8) [0x559a5648a568]
51  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x12827a) [0x559a5648927a]
52  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd5) [0x559a5649ac05]
53  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x123b) [0x559a5648b3cb]
54  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x12827a) [0x559a5648927a]
55  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalCodeWithName+0x47) [0x559a56488f07]
56  /datasets/pentschev/miniconda3/envs/gdf/bin/python(PyEval_EvalCodeEx+0x39) [0x559a56488eb9]
57  /datasets/pentschev/miniconda3/envs/gdf/bin/python(PyEval_EvalCode+0x1b) [0x559a565398bb]
58  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x206adc) [0x559a56567adc]
59  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x202c24) [0x559a56563c24]
60  /datasets/pentschev/miniconda3/envs/gdf/bin/python(PyRun_StringFlags+0x9d) [0x559a5655b7ed]
61  /datasets/pentschev/miniconda3/envs/gdf/bin/python(PyRun_SimpleStringFlags+0x3d) [0x559a5655b6bd]
=================================
[dgx13:61578:0:61578] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x448)
==== backtrace (tid:  61578) ====
 0  /datasets/pentschev/miniconda3/envs/gdf/lib/libucs.so.0(ucs_handle_error+0x2d4) [0x7f50b84c1614]
 1  /datasets/pentschev/miniconda3/envs/gdf/lib/libucs.so.0(+0x2e7ef) [0x7f50b84c17ef]
 2  /datasets/pentschev/miniconda3/envs/gdf/lib/libucs.so.0(+0x2eb14) [0x7f50b84c1b14]
 3  /lib/x86_64-linux-gnu/libpthread.so.0(+0x12980) [0x7f512dc41980]
 4  /datasets/pentschev/miniconda3/envs/gdf/lib/libucp.so.0(ucp_mem_type_unpack+0x14) [0x7f50b87463b4]
 5  /datasets/pentschev/miniconda3/envs/gdf/lib/libucp.so.0(ucp_rndv_data_handler+0x508) [0x7f50b8776a08]
 6  /datasets/pentschev/miniconda3/envs/gdf/lib/libuct.so.0(+0x20b5f) [0x7f50b8275b5f]
 7  /datasets/pentschev/miniconda3/envs/gdf/lib/libuct.so.0(+0x21134) [0x7f50b8276134]
 8  /datasets/pentschev/miniconda3/envs/gdf/lib/libuct.so.0(+0x23578) [0x7f50b8278578]
 9  /datasets/pentschev/miniconda3/envs/gdf/lib/libucs.so.0(ucs_event_set_wait+0xb9) [0x7f50b84cbc99]
10  /datasets/pentschev/miniconda3/envs/gdf/lib/libuct.so.0(uct_tcp_iface_progress+0x7b) [0x7f50b827861b]
11  /datasets/pentschev/miniconda3/envs/gdf/lib/libucp.so.0(ucp_worker_progress+0x6a) [0x7f50b8742caa]
12  /datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/ucp/_libs/ucx_api.cpython-39-x86_64-linux-gnu.so(+0x26c79) [0x7f50b89fcc79]
13  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x13eb08) [0x562d6560ab08]
14  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x5f82) [0x562d655fb112]
15  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x12827a) [0x562d655f427a]
16  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd5) [0x562d65605c05]
17  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x68b) [0x562d655f581b]
18  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x139ef3) [0x562d65605ef3]
19  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x147a16) [0x562d65613a16]
20  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x2579b1) [0x562d657239b1]
21  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0xe5817) [0x562d655b1817]
22  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x130f83) [0x562d655fcf83]
23  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x5ba6) [0x562d655fad36]
24  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x139ef3) [0x562d65605ef3]
25  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x68b) [0x562d655f581b]
26  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x139ef3) [0x562d65605ef3]
27  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x68b) [0x562d655f581b]
28  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x139ef3) [0x562d65605ef3]
29  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x68b) [0x562d655f581b]
30  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x139ef3) [0x562d65605ef3]
31  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x68b) [0x562d655f581b]
32  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x12827a) [0x562d655f427a]
33  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd5) [0x562d65605c05]
34  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x4e17) [0x562d655f9fa7]
35  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x12827a) [0x562d655f427a]
36  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x147935) [0x562d65613935]
37  /datasets/pentschev/miniconda3/envs/gdf/bin/python(PyObject_Call+0xb4) [0x562d65614104]
38  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x20efc8) [0x562d656dafc8]
39  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyObject_MakeTpCall+0x2fc) [0x562d655fe2bc]
40  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x402b) [0x562d655f91bb]
41  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x139ef3) [0x562d65605ef3]
42  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x147c72) [0x562d65613c72]
43  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x402b) [0x562d655f91bb]
44  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x139ef3) [0x562d65605ef3]
45  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x68b) [0x562d655f581b]
46  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x12827a) [0x562d655f427a]
47  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd5) [0x562d65605c05]
48  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x68b) [0x562d655f581b]
49  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x139ef3) [0x562d65605ef3]
50  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x3d8) [0x562d655f5568]
51  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x12827a) [0x562d655f427a]
52  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd5) [0x562d65605c05]
53  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x123b) [0x562d655f63cb]
54  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x12827a) [0x562d655f427a]
55  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalCodeWithName+0x47) [0x562d655f3f07]
56  /datasets/pentschev/miniconda3/envs/gdf/bin/python(PyEval_EvalCodeEx+0x39) [0x562d655f3eb9]
57  /datasets/pentschev/miniconda3/envs/gdf/bin/python(PyEval_EvalCode+0x1b) [0x562d656a48bb]
58  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x206adc) [0x562d656d2adc]
59  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x202c24) [0x562d656cec24]
60  /datasets/pentschev/miniconda3/envs/gdf/bin/python(PyRun_StringFlags+0x9d) [0x562d656c67ed]
61  /datasets/pentschev/miniconda3/envs/gdf/bin/python(PyRun_SimpleStringFlags+0x3d) [0x562d656c66bd]
=================================
[dgx13:61602:0:61602] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x448)
==== backtrace (tid:  61602) ====
 0  /datasets/pentschev/miniconda3/envs/gdf/lib/libucs.so.0(ucs_handle_error+0x2d4) [0x7f7f680cf614]
 1  /datasets/pentschev/miniconda3/envs/gdf/lib/libucs.so.0(+0x2e7ef) [0x7f7f680cf7ef]
 2  /datasets/pentschev/miniconda3/envs/gdf/lib/libucs.so.0(+0x2eb14) [0x7f7f680cfb14]
 3  /lib/x86_64-linux-gnu/libpthread.so.0(+0x12980) [0x7f7feb868980]
 4  /datasets/pentschev/miniconda3/envs/gdf/lib/libucp.so.0(ucp_mem_type_unpack+0x14) [0x7f7f683543b4]
 5  /datasets/pentschev/miniconda3/envs/gdf/lib/libucp.so.0(ucp_rndv_data_handler+0x508) [0x7f7f68384a08]
 6  /datasets/pentschev/miniconda3/envs/gdf/lib/libuct.so.0(+0x20b5f) [0x7f7f61de2b5f]
 7  /datasets/pentschev/miniconda3/envs/gdf/lib/libuct.so.0(+0x21134) [0x7f7f61de3134]
 8  /datasets/pentschev/miniconda3/envs/gdf/lib/libuct.so.0(+0x23578) [0x7f7f61de5578]
 9  /datasets/pentschev/miniconda3/envs/gdf/lib/libucs.so.0(ucs_event_set_wait+0xb9) [0x7f7f680d9c99]
10  /datasets/pentschev/miniconda3/envs/gdf/lib/libuct.so.0(uct_tcp_iface_progress+0x7b) [0x7f7f61de561b]
11  /datasets/pentschev/miniconda3/envs/gdf/lib/libucp.so.0(ucp_worker_progress+0x6a) [0x7f7f68350caa]
12  /datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/ucp/_libs/ucx_api.cpython-39-x86_64-linux-gnu.so(+0x26c79) [0x7f7f6860ac79]
13  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x13eb08) [0x562de49a4b08]
14  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x5f82) [0x562de4995112]
15  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x12827a) [0x562de498e27a]
16  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd5) [0x562de499fc05]
17  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x68b) [0x562de498f81b]
18  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x139ef3) [0x562de499fef3]
19  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x147a16) [0x562de49ada16]
20  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x2579b1) [0x562de4abd9b1]
21  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0xe5817) [0x562de494b817]
22  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x130f83) [0x562de4996f83]
23  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x5ba6) [0x562de4994d36]
24  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x139ef3) [0x562de499fef3]
25  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x68b) [0x562de498f81b]
26  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x139ef3) [0x562de499fef3]
27  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x68b) [0x562de498f81b]
28  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x139ef3) [0x562de499fef3]
29  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x68b) [0x562de498f81b]
30  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x139ef3) [0x562de499fef3]
31  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x68b) [0x562de498f81b]
32  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x12827a) [0x562de498e27a]
33  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd5) [0x562de499fc05]
34  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x4e17) [0x562de4993fa7]
35  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x12827a) [0x562de498e27a]
36  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x147935) [0x562de49ad935]
37  /datasets/pentschev/miniconda3/envs/gdf/bin/python(PyObject_Call+0xb4) [0x562de49ae104]
38  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x20efc8) [0x562de4a74fc8]
39  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyObject_MakeTpCall+0x2fc) [0x562de49982bc]
40  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x402b) [0x562de49931bb]
41  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x139ef3) [0x562de499fef3]
42  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x147c72) [0x562de49adc72]
43  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x402b) [0x562de49931bb]
44  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x139ef3) [0x562de499fef3]
45  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x68b) [0x562de498f81b]
46  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x12827a) [0x562de498e27a]
47  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd5) [0x562de499fc05]
48  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x68b) [0x562de498f81b]
49  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x139ef3) [0x562de499fef3]
50  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x3d8) [0x562de498f568]
51  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x12827a) [0x562de498e27a]
52  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd5) [0x562de499fc05]
53  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x123b) [0x562de49903cb]
54  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x12827a) [0x562de498e27a]
55  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalCodeWithName+0x47) [0x562de498df07]
56  /datasets/pentschev/miniconda3/envs/gdf/bin/python(PyEval_EvalCodeEx+0x39) [0x562de498deb9]
57  /datasets/pentschev/miniconda3/envs/gdf/bin/python(PyEval_EvalCode+0x1b) [0x562de4a3e8bb]
58  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x206adc) [0x562de4a6cadc]
59  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x202c24) [0x562de4a68c24]
60  /datasets/pentschev/miniconda3/envs/gdf/bin/python(PyRun_StringFlags+0x9d) [0x562de4a607ed]
61  /datasets/pentschev/miniconda3/envs/gdf/bin/python(PyRun_SimpleStringFlags+0x3d) [0x562de4a606bd]
=================================
[dgx13:61582:0:61582] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x448)
==== backtrace (tid:  61582) ====
 0  /datasets/pentschev/miniconda3/envs/gdf/lib/libucs.so.0(ucs_handle_error+0x2d4) [0x7fc2e103e614]
 1  /datasets/pentschev/miniconda3/envs/gdf/lib/libucs.so.0(+0x2e7ef) [0x7fc2e103e7ef]
 2  /datasets/pentschev/miniconda3/envs/gdf/lib/libucs.so.0(+0x2eb14) [0x7fc2e103eb14]
 3  /lib/x86_64-linux-gnu/libpthread.so.0(+0x12980) [0x7fc36487a980]
 4  /datasets/pentschev/miniconda3/envs/gdf/lib/libucp.so.0(ucp_mem_type_unpack+0x14) [0x7fc2e12c33b4]
 5  /datasets/pentschev/miniconda3/envs/gdf/lib/libucp.so.0(ucp_rndv_data_handler+0x508) [0x7fc2e12f3a08]
 6  /datasets/pentschev/miniconda3/envs/gdf/lib/libuct.so.0(+0x20b5f) [0x7fc2e0df2b5f]
 7  /datasets/pentschev/miniconda3/envs/gdf/lib/libuct.so.0(+0x21134) [0x7fc2e0df3134]
 8  /datasets/pentschev/miniconda3/envs/gdf/lib/libuct.so.0(+0x23578) [0x7fc2e0df5578]
 9  /datasets/pentschev/miniconda3/envs/gdf/lib/libucs.so.0(ucs_event_set_wait+0xb9) [0x7fc2e1048c99]
10  /datasets/pentschev/miniconda3/envs/gdf/lib/libuct.so.0(uct_tcp_iface_progress+0x7b) [0x7fc2e0df561b]
11  /datasets/pentschev/miniconda3/envs/gdf/lib/libucp.so.0(ucp_worker_progress+0x6a) [0x7fc2e12bfcaa]
12  /datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/ucp/_libs/ucx_api.cpython-39-x86_64-linux-gnu.so(+0x26c79) [0x7fc2e1579c79]
13  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x13eb08) [0x55ca8bd83b08]
14  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x5f82) [0x55ca8bd74112]
15  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x12827a) [0x55ca8bd6d27a]
16  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd5) [0x55ca8bd7ec05]
17  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x68b) [0x55ca8bd6e81b]
18  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x14e70e) [0x55ca8bd9370e]
19  /datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/lib-dynload/_asyncio.cpython-39-x86_64-linux-gnu.so(+0x82fe) [0x7fc2fedf72fe]
20  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyObject_MakeTpCall+0x2fc) [0x55ca8bd772bc]
21  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0xe5817) [0x55ca8bd2a817]
22  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x130f83) [0x55ca8bd75f83]
23  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x5ba6) [0x55ca8bd73d36]
24  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x139ef3) [0x55ca8bd7eef3]
25  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x68b) [0x55ca8bd6e81b]
26  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x139ef3) [0x55ca8bd7eef3]
27  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x68b) [0x55ca8bd6e81b]
28  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x139ef3) [0x55ca8bd7eef3]
29  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x68b) [0x55ca8bd6e81b]
30  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x139ef3) [0x55ca8bd7eef3]
31  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x68b) [0x55ca8bd6e81b]
32  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x12827a) [0x55ca8bd6d27a]
33  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd5) [0x55ca8bd7ec05]
34  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x4e17) [0x55ca8bd72fa7]
35  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x12827a) [0x55ca8bd6d27a]
36  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x147935) [0x55ca8bd8c935]
37  /datasets/pentschev/miniconda3/envs/gdf/bin/python(PyObject_Call+0xb4) [0x55ca8bd8d104]
38  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x20efc8) [0x55ca8be53fc8]
39  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyObject_MakeTpCall+0x2fc) [0x55ca8bd772bc]
40  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x402b) [0x55ca8bd721bb]
41  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x139ef3) [0x55ca8bd7eef3]
42  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x147c72) [0x55ca8bd8cc72]
43  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x402b) [0x55ca8bd721bb]
44  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x139ef3) [0x55ca8bd7eef3]
45  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x68b) [0x55ca8bd6e81b]
46  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x12827a) [0x55ca8bd6d27a]
47  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd5) [0x55ca8bd7ec05]
48  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x68b) [0x55ca8bd6e81b]
49  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x139ef3) [0x55ca8bd7eef3]
50  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x3d8) [0x55ca8bd6e568]
51  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x12827a) [0x55ca8bd6d27a]
52  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd5) [0x55ca8bd7ec05]
53  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x123b) [0x55ca8bd6f3cb]
54  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x12827a) [0x55ca8bd6d27a]
55  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalCodeWithName+0x47) [0x55ca8bd6cf07]
56  /datasets/pentschev/miniconda3/envs/gdf/bin/python(PyEval_EvalCodeEx+0x39) [0x55ca8bd6ceb9]
57  /datasets/pentschev/miniconda3/envs/gdf/bin/python(PyEval_EvalCode+0x1b) [0x55ca8be1d8bb]
58  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x206adc) [0x55ca8be4badc]
59  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x202c24) [0x55ca8be47c24]
60  /datasets/pentschev/miniconda3/envs/gdf/bin/python(PyRun_StringFlags+0x9d) [0x55ca8be3f7ed]
61  /datasets/pentschev/miniconda3/envs/gdf/bin/python(PyRun_SimpleStringFlags+0x3d) [0x55ca8be3f6bd]
=================================
[dgx13:61593:0:61593] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x448)
==== backtrace (tid:  61593) ====
 0  /datasets/pentschev/miniconda3/envs/gdf/lib/libucs.so.0(ucs_handle_error+0x2d4) [0x7fee08334614]
 1  /datasets/pentschev/miniconda3/envs/gdf/lib/libucs.so.0(+0x2e7ef) [0x7fee083347ef]
 2  /datasets/pentschev/miniconda3/envs/gdf/lib/libucs.so.0(+0x2eb14) [0x7fee08334b14]
 3  /lib/x86_64-linux-gnu/libpthread.so.0(+0x12980) [0x7fee8baa2980]
 4  /datasets/pentschev/miniconda3/envs/gdf/lib/libucp.so.0(ucp_mem_type_unpack+0x14) [0x7fee085b93b4]
 5  /datasets/pentschev/miniconda3/envs/gdf/lib/libucp.so.0(ucp_rndv_data_handler+0x508) [0x7fee085e9a08]
 6  /datasets/pentschev/miniconda3/envs/gdf/lib/libuct.so.0(+0x20b5f) [0x7fee080e8b5f]
 7  /datasets/pentschev/miniconda3/envs/gdf/lib/libuct.so.0(+0x21134) [0x7fee080e9134]
 8  /datasets/pentschev/miniconda3/envs/gdf/lib/libuct.so.0(+0x23578) [0x7fee080eb578]
 9  /datasets/pentschev/miniconda3/envs/gdf/lib/libucs.so.0(ucs_event_set_wait+0xb9) [0x7fee0833ec99]
10  /datasets/pentschev/miniconda3/envs/gdf/lib/libuct.so.0(uct_tcp_iface_progress+0x7b) [0x7fee080eb61b]
11  /datasets/pentschev/miniconda3/envs/gdf/lib/libucp.so.0(ucp_worker_progress+0x6a) [0x7fee085b5caa]
12  /datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/ucp/_libs/ucx_api.cpython-39-x86_64-linux-gnu.so(+0x26c79) [0x7fee0886fc79]
13  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x13eb08) [0x55dfc2fc0b08]
14  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x5f82) [0x55dfc2fb1112]
15  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x12827a) [0x55dfc2faa27a]
16  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd5) [0x55dfc2fbbc05]
17  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x68b) [0x55dfc2fab81b]
18  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x139ef3) [0x55dfc2fbbef3]
19  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x147a16) [0x55dfc2fc9a16]
20  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x2579b1) [0x55dfc30d99b1]
21  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0xe5817) [0x55dfc2f67817]
22  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x130f83) [0x55dfc2fb2f83]
23  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x5ba6) [0x55dfc2fb0d36]
24  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x139ef3) [0x55dfc2fbbef3]
25  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x68b) [0x55dfc2fab81b]
26  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x139ef3) [0x55dfc2fbbef3]
27  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x68b) [0x55dfc2fab81b]
28  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x139ef3) [0x55dfc2fbbef3]
29  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x68b) [0x55dfc2fab81b]
30  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x139ef3) [0x55dfc2fbbef3]
31  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x68b) [0x55dfc2fab81b]
32  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x12827a) [0x55dfc2faa27a]
33  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd5) [0x55dfc2fbbc05]
34  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x4e17) [0x55dfc2faffa7]
35  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x12827a) [0x55dfc2faa27a]
36  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x147935) [0x55dfc2fc9935]
37  /datasets/pentschev/miniconda3/envs/gdf/bin/python(PyObject_Call+0xb4) [0x55dfc2fca104]
38  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x20efc8) [0x55dfc3090fc8]
39  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyObject_MakeTpCall+0x2fc) [0x55dfc2fb42bc]
40  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x402b) [0x55dfc2faf1bb]
41  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x139ef3) [0x55dfc2fbbef3]
42  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x147c72) [0x55dfc2fc9c72]
43  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x402b) [0x55dfc2faf1bb]
44  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x139ef3) [0x55dfc2fbbef3]
45  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x68b) [0x55dfc2fab81b]
46  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x12827a) [0x55dfc2faa27a]
47  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd5) [0x55dfc2fbbc05]
48  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x68b) [0x55dfc2fab81b]
49  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x139ef3) [0x55dfc2fbbef3]
50  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x3d8) [0x55dfc2fab568]
51  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x12827a) [0x55dfc2faa27a]
52  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyFunction_Vectorcall+0xd5) [0x55dfc2fbbc05]
53  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalFrameDefault+0x123b) [0x55dfc2fac3cb]
54  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x12827a) [0x55dfc2faa27a]
55  /datasets/pentschev/miniconda3/envs/gdf/bin/python(_PyEval_EvalCodeWithName+0x47) [0x55dfc2fa9f07]
56  /datasets/pentschev/miniconda3/envs/gdf/bin/python(PyEval_EvalCodeEx+0x39) [0x55dfc2fa9eb9]
57  /datasets/pentschev/miniconda3/envs/gdf/bin/python(PyEval_EvalCode+0x1b) [0x55dfc305a8bb]
58  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x206adc) [0x55dfc3088adc]
59  /datasets/pentschev/miniconda3/envs/gdf/bin/python(+0x202c24) [0x55dfc3084c24]
60  /datasets/pentschev/miniconda3/envs/gdf/bin/python(PyRun_StringFlags+0x9d) [0x55dfc307c7ed]
61  /datasets/pentschev/miniconda3/envs/gdf/bin/python(PyRun_SimpleStringFlags+0x3d) [0x55dfc307c6bd]
=================================
2023-02-08 00:02:13,696 - distributed.worker - ERROR - Worker stream died during communication: ucx://127.0.0.1:46039
Traceback (most recent call last):
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 349, in read
    await self.ep.recv(msg)
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/ucp/core.py", line 725, in recv
    ret = await comm.tag_recv(self._ep, buffer, nbytes, tag, name=log)
ucp._libs.exceptions.UCXCanceled: <[Recv #003] ep: 0x7efeec1c0100, tag: 0xdb34ea91e2d24b82, nbytes: 16, type: <class 'numpy.ndarray'>>: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/worker.py", line 2058, in gather_dep
    response = await get_data_from_worker(
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/worker.py", line 2872, in get_data_from_worker
    return await retry_operation(_get_data, operation="get_data_from_worker")
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/utils_comm.py", line 419, in retry_operation
    return await retry(
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/utils_comm.py", line 404, in retry
    return await coro()
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/worker.py", line 2852, in _get_data
    response = await send_recv(
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/core.py", line 986, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/utils.py", line 741, in wrapper
    return await func(*args, **kwargs)
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 367, in read
    raise CommClosedError(
distributed.comm.core.CommClosedError: Connection closed by writer.
Inner exception: UCXCanceled("<[Recv #003] ep: 0x7efeec1c0100, tag: 0xdb34ea91e2d24b82, nbytes: 16, type: <class 'numpy.ndarray'>>: ")
2023-02-08 00:02:13,715 - distributed.worker - ERROR - Worker stream died during communication: ucx://127.0.0.1:40403
Traceback (most recent call last):
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 349, in read
    await self.ep.recv(msg)
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/ucp/core.py", line 725, in recv
    ret = await comm.tag_recv(self._ep, buffer, nbytes, tag, name=log)
ucp._libs.exceptions.UCXCanceled: <[Recv #008] ep: 0x7efeec1c0140, tag: 0x593968dc03f0e474, nbytes: 16, type: <class 'numpy.ndarray'>>: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/worker.py", line 2058, in gather_dep
    response = await get_data_from_worker(
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/worker.py", line 2872, in get_data_from_worker
    return await retry_operation(_get_data, operation="get_data_from_worker")
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/utils_comm.py", line 419, in retry_operation
    return await retry(
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/utils_comm.py", line 404, in retry
    return await coro()
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/worker.py", line 2852, in _get_data
    response = await send_recv(
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/core.py", line 986, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/utils.py", line 741, in wrapper
    return await func(*args, **kwargs)
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 367, in read
    raise CommClosedError(
distributed.comm.core.CommClosedError: Connection closed by writer.
Inner exception: UCXCanceled("<[Recv #008] ep: 0x7efeec1c0140, tag: 0x593968dc03f0e474, nbytes: 16, type: <class 'numpy.ndarray'>>: ")
2023-02-08 00:02:13,735 - distributed.worker - ERROR - Worker stream died during communication: ucx://127.0.0.1:57633
Traceback (most recent call last):
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 391, in read
    await self.ep.recv(each_frame)
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/ucp/core.py", line 725, in recv
    ret = await comm.tag_recv(self._ep, buffer, nbytes, tag, name=log)
ucp._libs.exceptions.UCXError: <[Recv #007] ep: 0x7efeec1c0180, tag: 0x8f1f513470e6120b, nbytes: 50000000, type: <class 'rmm._lib.device_buffer.DeviceBuffer'>>: Connection reset by remote peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/worker.py", line 2058, in gather_dep
    response = await get_data_from_worker(
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/worker.py", line 2872, in get_data_from_worker
    return await retry_operation(_get_data, operation="get_data_from_worker")
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/utils_comm.py", line 419, in retry_operation
    return await retry(
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/utils_comm.py", line 404, in retry
    return await coro()
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/worker.py", line 2852, in _get_data
    response = await send_recv(
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/core.py", line 986, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/utils.py", line 741, in wrapper
    return await func(*args, **kwargs)
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 397, in read
    raise CommClosedError(
distributed.comm.core.CommClosedError: Connection closed by writer.
Inner exception: UCXError("<[Recv #007] ep: 0x7efeec1c0180, tag: 0x8f1f513470e6120b, nbytes: 50000000, type: <class 'rmm._lib.device_buffer.DeviceBuffer'>>: Connection reset by remote peer")
2023-02-08 00:02:13,736 - distributed.worker - ERROR - failed during get data with ucx://127.0.0.1:38107 -> ucx://127.0.0.1:57633
Traceback (most recent call last):
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 333, in write
    await self.ep.send(each_frame)
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/ucp/core.py", line 650, in send
    return await comm.tag_send(self._ep, buffer, nbytes, tag, name=log)
ucp._libs.exceptions.UCXError: <[Send #007] ep: 0x7efeec1c02c0, tag: 0x31dd505415891a61, nbytes: 50000000, type: <class 'cupy.ndarray'>>: Connection reset by remote peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/worker.py", line 1766, in get_data
    compressed = await comm.write(msg, serializers=serializers)
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/utils.py", line 741, in wrapper
    return await func(*args, **kwargs)
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 337, in write
    raise CommClosedError("While writing, the connection was closed")
distributed.comm.core.CommClosedError: While writing, the connection was closed
2023-02-08 00:02:13,735 - distributed.worker - ERROR - Worker stream died during communication: ucx://127.0.0.1:57633
Traceback (most recent call last):
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 349, in read
    await self.ep.recv(msg)
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/ucp/core.py", line 725, in recv
    ret = await comm.tag_recv(self._ep, buffer, nbytes, tag, name=log)
ucp._libs.exceptions.UCXCanceled: <[Recv #003] ep: 0x7facbc0c4180, tag: 0xdd0c8d8f4e1bca8e, nbytes: 16, type: <class 'numpy.ndarray'>>: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/worker.py", line 2058, in gather_dep
    response = await get_data_from_worker(
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/worker.py", line 2872, in get_data_from_worker
    return await retry_operation(_get_data, operation="get_data_from_worker")
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/utils_comm.py", line 419, in retry_operation
    return await retry(
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/utils_comm.py", line 404, in retry
    return await coro()
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/worker.py", line 2852, in _get_data
    response = await send_recv(
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/core.py", line 986, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/utils.py", line 741, in wrapper
    return await func(*args, **kwargs)
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 367, in read
    raise CommClosedError(
distributed.comm.core.CommClosedError: Connection closed by writer.
Inner exception: UCXCanceled("<[Recv #003] ep: 0x7facbc0c4180, tag: 0xdd0c8d8f4e1bca8e, nbytes: 16, type: <class 'numpy.ndarray'>>: ")
2023-02-08 00:02:13,742 - distributed.nanny - WARNING - Restarting worker
2023-02-08 00:02:13,782 - distributed.worker - ERROR - failed during get data with ucx://127.0.0.1:51363 -> ucx://127.0.0.1:45347
Traceback (most recent call last):
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 333, in write
    await self.ep.send(each_frame)
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/ucp/core.py", line 650, in send
    return await comm.tag_send(self._ep, buffer, nbytes, tag, name=log)
ucp._libs.exceptions.UCXError: <[Send #007] ep: 0x7f599c0b7280, tag: 0xbacd66587fde1a3, nbytes: 50000000, type: <class 'cupy.ndarray'>>: Connection reset by remote peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/worker.py", line 1766, in get_data
    compressed = await comm.write(msg, serializers=serializers)
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/utils.py", line 741, in wrapper
    return await func(*args, **kwargs)
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 337, in write
    raise CommClosedError("While writing, the connection was closed")
distributed.comm.core.CommClosedError: While writing, the connection was closed
2023-02-08 00:02:13,785 - distributed.worker - ERROR - Worker stream died during communication: ucx://127.0.0.1:57633
Traceback (most recent call last):
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 349, in read
    await self.ep.recv(msg)
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/ucp/core.py", line 725, in recv
    ret = await comm.tag_recv(self._ep, buffer, nbytes, tag, name=log)
ucp._libs.exceptions.UCXCanceled: <[Recv #003] ep: 0x7f599c0b7180, tag: 0x4675bfe2df715c3f, nbytes: 16, type: <class 'numpy.ndarray'>>: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/worker.py", line 2058, in gather_dep
    response = await get_data_from_worker(
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/worker.py", line 2872, in get_data_from_worker
    return await retry_operation(_get_data, operation="get_data_from_worker")
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/utils_comm.py", line 419, in retry_operation
    return await retry(
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/utils_comm.py", line 404, in retry
    return await coro()
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/worker.py", line 2852, in _get_data
    response = await send_recv(
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/core.py", line 986, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/utils.py", line 741, in wrapper
    return await func(*args, **kwargs)
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 367, in read
    raise CommClosedError(
distributed.comm.core.CommClosedError: Connection closed by writer.
Inner exception: UCXCanceled("<[Recv #003] ep: 0x7f599c0b7180, tag: 0x4675bfe2df715c3f, nbytes: 16, type: <class 'numpy.ndarray'>>: ")
2023-02-08 00:02:13,786 - distributed.worker - ERROR - failed during get data with ucx://127.0.0.1:51363 -> ucx://127.0.0.1:46039
Traceback (most recent call last):
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 349, in read
    await self.ep.recv(msg)
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/ucp/core.py", line 725, in recv
    ret = await comm.tag_recv(self._ep, buffer, nbytes, tag, name=log)
ucp._libs.exceptions.UCXCanceled: <[Recv #006] ep: 0x7f599c0b72c0, tag: 0x751aebcf72e7c8fa, nbytes: 16, type: <class 'numpy.ndarray'>>: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/worker.py", line 1767, in get_data
    response = await comm.read(deserializers=serializers)
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/utils.py", line 741, in wrapper
    return await func(*args, **kwargs)
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 367, in read
    raise CommClosedError(
distributed.comm.core.CommClosedError: Connection closed by writer.
Inner exception: UCXCanceled("<[Recv #006] ep: 0x7f599c0b72c0, tag: 0x751aebcf72e7c8fa, nbytes: 16, type: <class 'numpy.ndarray'>>: ")
2023-02-08 00:02:13,788 - distributed.nanny - WARNING - Restarting worker
2023-02-08 00:02:13,799 - distributed.worker - ERROR - Worker stream died during communication: ucx://127.0.0.1:38165
Traceback (most recent call last):
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 391, in read
    await self.ep.recv(each_frame)
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/ucp/core.py", line 725, in recv
    ret = await comm.tag_recv(self._ep, buffer, nbytes, tag, name=log)
ucp._libs.exceptions.UCXError: <[Recv #007] ep: 0x7efeec1c01c0, tag: 0xe1f9e3fc6d7b7e60, nbytes: 50000000, type: <class 'rmm._lib.device_buffer.DeviceBuffer'>>: Connection reset by remote peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/worker.py", line 2058, in gather_dep
    response = await get_data_from_worker(
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/worker.py", line 2872, in get_data_from_worker
    return await retry_operation(_get_data, operation="get_data_from_worker")
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/utils_comm.py", line 419, in retry_operation
    return await retry(
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/utils_comm.py", line 404, in retry
    return await coro()
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/worker.py", line 2852, in _get_data
    response = await send_recv(
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/core.py", line 986, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/utils.py", line 741, in wrapper
    return await func(*args, **kwargs)
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 397, in read
    raise CommClosedError(
distributed.comm.core.CommClosedError: Connection closed by writer.
Inner exception: UCXError("<[Recv #007] ep: 0x7efeec1c01c0, tag: 0xe1f9e3fc6d7b7e60, nbytes: 50000000, type: <class 'rmm._lib.device_buffer.DeviceBuffer'>>: Connection reset by remote peer")
2023-02-08 00:02:13,799 - distributed.worker - ERROR - failed during get data with ucx://127.0.0.1:38107 -> ucx://127.0.0.1:38165
Traceback (most recent call last):
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 333, in write
    await self.ep.send(each_frame)
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/ucp/core.py", line 650, in send
    return await comm.tag_send(self._ep, buffer, nbytes, tag, name=log)
ucp._libs.exceptions.UCXError: <[Send #007] ep: 0x7efeec1c0200, tag: 0x16f053a1909a5fc1, nbytes: 50000000, type: <class 'cupy.ndarray'>>: Connection reset by remote peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/worker.py", line 1766, in get_data
    compressed = await comm.write(msg, serializers=serializers)
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/utils.py", line 741, in wrapper
    return await func(*args, **kwargs)
  File "/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/site-packages/distributed/comm/ucx.py", line 337, in write
    raise CommClosedError("While writing, the connection was closed")
distributed.comm.core.CommClosedError: While writing, the connection was closed
2023-02-08 00:02:13,844 - distributed.nanny - WARNING - Restarting worker
2023-02-08 00:02:13,883 - distributed.nanny - WARNING - Restarting worker
2023-02-08 00:02:13,963 - distributed.nanny - WARNING - Restarting worker
2023-02-08 00:02:15,579 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-02-08 00:02:15,579 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-02-08 00:02:15,621 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-02-08 00:02:15,621 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-02-08 00:02:15,627 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-02-08 00:02:15,627 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-02-08 00:02:15,751 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-02-08 00:02:15,751 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2023-02-08 00:02:15,778 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2023-02-08 00:02:15,778 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
/datasets/pentschev/miniconda3/envs/gdf/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 48 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
